// Mock data for the Projects page. Mirrors the reference UI where each
// "project" is a logical grouping of shipments (a batch) rather than a
// single MBL. When the real backend lands, replace the exports below with
// a `useProjectsData` query that returns the same shapes — the components
// only care about the shape, not the source.

export type KpiTrend = "up" | "down";

export type ProjectKpi = {
  id: "demurrage" | "perDiem" | "arriving";
  /** i18n key for the card label */
  labelKey: string;
  value: number;
  deltaPercent: number; // e.g. 8.3 or -2.1
  trend: KpiTrend;
  iconName: "AlertTriangle" | "Clock" | "Ship";
  /** Tailwind bg class for the soft pastel card surface */
  tint: string;
  /** Tailwind bg class for the small icon badge on the top-right */
  iconBadgeTint: string;
  iconColor: string;
};

export const PROJECT_KPIS: ProjectKpi[] = [
  {
    id: "demurrage",
    labelKey: "pages.projects.kpi.demurrage",
    value: 12,
    deltaPercent: 8.3,
    trend: "up",
    iconName: "AlertTriangle",
    tint: "bg-[#FFEDE6]",
    iconBadgeTint: "bg-[#FFD7C4]",
    iconColor: "#C2410C",
  },
  {
    id: "perDiem",
    labelKey: "pages.projects.kpi.perDiem",
    value: 7,
    deltaPercent: -2.1,
    trend: "down",
    iconName: "Clock",
    tint: "bg-[#FFF6DC]",
    iconBadgeTint: "bg-[#FAE6B3]",
    iconColor: "#92400E",
  },
  {
    id: "arriving",
    labelKey: "pages.projects.kpi.arriving",
    value: 24,
    deltaPercent: 15.0,
    trend: "up",
    iconName: "Ship",
    tint: "bg-[#E4F2EA]",
    iconBadgeTint: "bg-[#C2E3D1]",
    iconColor: "#166534",
  },
];

export type ProjectStatus =
  | "in-transit"
  | "at-port"
  | "delivered"
  | "delayed"
  | "pending";

export type ProjectItem = {
  id: string;
  name: string;
  etaLabel: string;
  carrierName: string;
  /** Hex for the small carrier badge background */
  carrierBadge: string;
  carrierInitial: string;
  assigneeAvatar: string;
  status: ProjectStatus;
  containersDone: number;
  containersTotal: number;
  progress: number;
};

export const PROJECT_ITEMS: ProjectItem[] = [
  {
    id: "p1",
    name: "Busan → LAX Q4 Electronics",
    etaLabel: "Nov 10, 2026",
    carrierName: "Maersk",
    carrierBadge: "#E8F1FF",
    carrierInitial: "M",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-lee",
    status: "in-transit",
    containersDone: 15,
    containersTotal: 20,
    progress: 75,
  },
  {
    id: "p2",
    name: "Shanghai → NY Apparel",
    etaLabel: "Nov 15, 2026",
    carrierName: "COSCO",
    carrierBadge: "#FFE8EE",
    carrierInitial: "C",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-kim",
    status: "pending",
    containersDone: 5,
    containersTotal: 12,
    progress: 42,
  },
  {
    id: "p3",
    name: "Yantian → Oakland Retail",
    etaLabel: "Oct 28, 2026",
    carrierName: "ONE",
    carrierBadge: "#FFE0E0",
    carrierInitial: "O",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-park",
    status: "delivered",
    containersDone: 18,
    containersTotal: 18,
    progress: 100,
  },
  {
    id: "p4",
    name: "Busan → Savannah HMM Lane",
    etaLabel: "Dec 2, 2026",
    carrierName: "HMM",
    carrierBadge: "#E8FAF0",
    carrierInitial: "H",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-jo",
    status: "in-transit",
    containersDone: 9,
    containersTotal: 16,
    progress: 56,
  },
  {
    id: "p5",
    name: "Vancouver → Incheon Return",
    etaLabel: "Nov 3, 2026",
    carrierName: "SM Line",
    carrierBadge: "#FFF5D6",
    carrierInitial: "S",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-choi",
    status: "delayed",
    containersDone: 4,
    containersTotal: 10,
    progress: 40,
  },
  {
    id: "p6",
    name: "Ningbo → Long Beach Chemicals",
    etaLabel: "Nov 22, 2026",
    carrierName: "ZIM",
    carrierBadge: "#E7E6FA",
    carrierInitial: "Z",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-han",
    status: "in-transit",
    containersDone: 11,
    containersTotal: 22,
    progress: 50,
  },
  {
    id: "p7",
    name: "Busan → Tokyo Express",
    etaLabel: "Nov 6, 2026",
    carrierName: "Yang Ming",
    carrierBadge: "#FFF3D6",
    carrierInitial: "Y",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-seo",
    status: "at-port",
    containersDone: 6,
    containersTotal: 8,
    progress: 88,
  },
  {
    id: "p8",
    name: "Qingdao → Houston Auto Parts",
    etaLabel: "Dec 18, 2026",
    carrierName: "Evergreen",
    carrierBadge: "#E8F5E9",
    carrierInitial: "E",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-shin",
    status: "pending",
    containersDone: 2,
    containersTotal: 14,
    progress: 18,
  },
  {
    id: "p9",
    name: "Antwerp → Busan Luxury Goods",
    etaLabel: "Nov 12, 2026",
    carrierName: "MSC",
    carrierBadge: "#F7E8FA",
    carrierInitial: "M",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-yoon",
    status: "in-transit",
    containersDone: 3,
    containersTotal: 6,
    progress: 55,
  },
  {
    id: "p10",
    name: "Busan → Hamburg Batteries",
    etaLabel: "Jan 5, 2027",
    carrierName: "Hapag-Lloyd",
    carrierBadge: "#FFE7DB",
    carrierInitial: "H",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-baek",
    status: "pending",
    containersDone: 0,
    containersTotal: 24,
    progress: 5,
  },
  {
    id: "p11",
    name: "Kaohsiung → Seattle Textiles",
    etaLabel: "Nov 19, 2026",
    carrierName: "Wan Hai",
    carrierBadge: "#E6F3FF",
    carrierInitial: "W",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-oh",
    status: "in-transit",
    containersDone: 7,
    containersTotal: 11,
    progress: 64,
  },
  {
    id: "p12",
    name: "Busan → Rotterdam Q1 Steel",
    etaLabel: "Jan 22, 2027",
    carrierName: "Hamburg Süd",
    carrierBadge: "#FEE8E8",
    carrierInitial: "H",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-chung",
    status: "delayed",
    containersDone: 8,
    containersTotal: 20,
    progress: 45,
  },
  {
    id: "p13",
    name: "Shenzhen → Miami Consumer Goods",
    etaLabel: "Dec 8, 2026",
    carrierName: "Maersk",
    carrierBadge: "#E8F1FF",
    carrierInitial: "M",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-jeon",
    status: "in-transit",
    containersDone: 13,
    containersTotal: 18,
    progress: 72,
  },
  {
    id: "p14",
    name: "Tokyo → Busan Components",
    etaLabel: "Nov 4, 2026",
    carrierName: "ONE",
    carrierBadge: "#FFE0E0",
    carrierInitial: "O",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-moon",
    status: "at-port",
    containersDone: 5,
    containersTotal: 6,
    progress: 92,
  },
  {
    id: "p15",
    name: "Busan → Sydney Q4 Cosmetics",
    etaLabel: "Dec 30, 2026",
    carrierName: "COSCO",
    carrierBadge: "#FFE8EE",
    carrierInitial: "C",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-jung",
    status: "in-transit",
    containersDone: 4,
    containersTotal: 10,
    progress: 40,
  },
  {
    id: "p16",
    name: "Incheon → Seattle Fresh Foods",
    etaLabel: "Oct 30, 2026",
    carrierName: "HMM",
    carrierBadge: "#E8FAF0",
    carrierInitial: "H",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-son",
    status: "delivered",
    containersDone: 8,
    containersTotal: 8,
    progress: 100,
  },
  {
    id: "p17",
    name: "Dalian → Oakland Furniture",
    etaLabel: "Dec 1, 2026",
    carrierName: "SM Line",
    carrierBadge: "#FFF5D6",
    carrierInitial: "S",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-kang",
    status: "pending",
    containersDone: 1,
    containersTotal: 9,
    progress: 10,
  },
  {
    id: "p18",
    name: "Busan → Felixstowe Machinery",
    etaLabel: "Jan 10, 2027",
    carrierName: "Hapag-Lloyd",
    carrierBadge: "#FFE7DB",
    carrierInitial: "H",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-hwang",
    status: "delayed",
    containersDone: 6,
    containersTotal: 15,
    progress: 38,
  },
  {
    id: "p19",
    name: "Ningbo → Vancouver Retail",
    etaLabel: "Nov 28, 2026",
    carrierName: "MSC",
    carrierBadge: "#F7E8FA",
    carrierInitial: "M",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-im",
    status: "in-transit",
    containersDone: 17,
    containersTotal: 25,
    progress: 68,
  },
  {
    id: "p20",
    name: "Busan → Montreal Batteries",
    etaLabel: "Dec 15, 2026",
    carrierName: "ZIM",
    carrierBadge: "#E7E6FA",
    carrierInitial: "Z",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-noh",
    status: "in-transit",
    containersDone: 9,
    containersTotal: 14,
    progress: 62,
  },
  {
    id: "p21",
    name: "Qingdao → Los Angeles Q4 Auto",
    etaLabel: "Nov 8, 2026",
    carrierName: "Evergreen",
    carrierBadge: "#E8F5E9",
    carrierInitial: "E",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-yi",
    status: "at-port",
    containersDone: 10,
    containersTotal: 12,
    progress: 90,
  },
  {
    id: "p22",
    name: "Busan → Chennai Textiles",
    etaLabel: "Dec 22, 2026",
    carrierName: "Yang Ming",
    carrierBadge: "#FFF3D6",
    carrierInitial: "Y",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-ahn",
    status: "in-transit",
    containersDone: 7,
    containersTotal: 16,
    progress: 48,
  },
  {
    id: "p23",
    name: "Xiamen → Houston Toys",
    etaLabel: "Oct 25, 2026",
    carrierName: "Wan Hai",
    carrierBadge: "#E6F3FF",
    carrierInitial: "W",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-ryu",
    status: "delivered",
    containersDone: 14,
    containersTotal: 14,
    progress: 100,
  },
  {
    id: "p24",
    name: "Busan → Lisbon Specialty Gear",
    etaLabel: "Jan 2, 2027",
    carrierName: "Maersk",
    carrierBadge: "#E8F1FF",
    carrierInitial: "M",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-bae",
    status: "pending",
    containersDone: 0,
    containersTotal: 8,
    progress: 3,
  },
  {
    id: "p25",
    name: "Tianjin → Charleston Plastics",
    etaLabel: "Nov 26, 2026",
    carrierName: "COSCO",
    carrierBadge: "#FFE8EE",
    carrierInitial: "C",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-nam",
    status: "delayed",
    containersDone: 3,
    containersTotal: 12,
    progress: 28,
  },
  {
    id: "p26",
    name: "Busan → Manila Appliances",
    etaLabel: "Nov 30, 2026",
    carrierName: "HMM",
    carrierBadge: "#E8FAF0",
    carrierInitial: "H",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-seok",
    status: "in-transit",
    containersDone: 6,
    containersTotal: 10,
    progress: 60,
  },
  {
    id: "p27",
    name: "Laem Chabang → Busan Rubber",
    etaLabel: "Nov 14, 2026",
    carrierName: "ONE",
    carrierBadge: "#FFE0E0",
    carrierInitial: "O",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-gil",
    status: "in-transit",
    containersDone: 8,
    containersTotal: 11,
    progress: 78,
  },
  {
    id: "p28",
    name: "Busan → Dubai Electronics",
    etaLabel: "Dec 12, 2026",
    carrierName: "MSC",
    carrierBadge: "#F7E8FA",
    carrierInitial: "M",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-woo",
    status: "in-transit",
    containersDone: 12,
    containersTotal: 20,
    progress: 65,
  },
  {
    id: "p29",
    name: "Haiphong → Portland Apparel",
    etaLabel: "Oct 22, 2026",
    carrierName: "Evergreen",
    carrierBadge: "#E8F5E9",
    carrierInitial: "E",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-pyun",
    status: "delivered",
    containersDone: 9,
    containersTotal: 9,
    progress: 100,
  },
  {
    id: "p30",
    name: "Busan → Santos Q1 Coffee Return",
    etaLabel: "Jan 28, 2027",
    carrierName: "Hamburg Süd",
    carrierBadge: "#FEE8E8",
    carrierInitial: "H",
    assigneeAvatar: "https://i.pravatar.cc/48?u=manager-go",
    status: "pending",
    containersDone: 0,
    containersTotal: 18,
    progress: 2,
  },
];
